# Generated by Django 4.2.5 on 2025-03-29 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
